length=float(input("Enter the length of cuboid = "))
width=float(input("Enter the width of cuboid = "))
height=float(input("Enter the height of cuboid = "))
area=2*(length*width+length*height+height*width)
print("Area of cuboid is ",area)
